version: "2"

services:
  jenkins:
    image: 'jenkinsci/blueocean:latest'
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - 'JENKINS_OPTS=--httpPort=8080 --httpsPort=8443'


volumes:
  jenkins_home:
  