Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "ansible.box"

  config.vm.provider "virtualbox" do |v|
    v.memory = 7792
    v.cpus = 2
  end

  config.vm.provision "shell" do |shell|
    shell.path = "provision.sh"
  end

  config.vm.network "forwarded_port", guest: 8080, host: 2345, id: "pet"
  config.vm.network "forwarded_port", guest: 80, host: 2346, id: "nginx2"
  config.vm.network "public_network"
end
